CREATE TABLE cliente 
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    nome VARCHAR(128),
    cognome VARCHAR(128),
    username VARCHAR(128),
    password VARCHAR(32)

);

CREATE TABLE venditore
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    cognome VARCHAR(128),
    username VARCHAR(128),
    password VARCHAR(32)

);

CREATE TABLE saldo_conti
(
    id INTEGER,
    utente_id INTEGER,
    importo DOUBLE,
    PRIMARY KEY (id, utente_id),
    FOREIGN KEY (utente_id) REFERENCES cliente(id),
    FOREIGN KEY (utente_id) REFERENCES venditore(id)
);

CREATE TABLE tipo_oggetto
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    descrizione VARCHAR(128)

    
);

CREATE TABLE oggetto
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_id INTEGER,
    descrizione VARCHAR(128),
    quantita DOUBLE,
    prezzo DOUBLE,
    FOREIGN KEY (tipo_id) REFERENCES tipo_oggetto(id)
);



INSERT INTO cliente(id, nome, cognome, username, password)
VALUES (default, 'Giuseppe', 'Cocco', 'GiuseppeC', 'giuseppec'),
(default, 'Annalisa', 'Bianchi', 'AnnalisaB', 'annlisab'),
(default, 'Davide', 'Rossi', 'DavideR', 'davider'),
(default, 'Gabriele', 'Verdi', 'GabrieleV', 'gabrielev');

INSERT INTO venditore(id, nome, cognome, username, password)
VALUES (default, 'Marco', 'Marchi', 'MarcoC', 'marcov'),
(default, 'Giorgio', 'Giorgi', 'GiorgioV', 'giorgiov');

INSERT INTO tipo_oggetto(id, descrizione)
VALUES (default, 'Scarpa'),
(default, 'Abbigliamento'),
(default, 'Accessori');

INSERT INTO oggetto(id, tipo_id, descrizione, quantita, prezzo)
VALUES (default, 1, 'Scarpa A', 1, 80),
(default, 2, 'Panta lungo B', 1, 40),
(default, 2, 'Maglia ML A', 1, 50),
(default, 2, 'T shirt C', 1, 25),
(default, 2, 'Panta 3/4 A', 1, 35),
(default, 3, 'Calza', 1, 10);